version: '2.1'

services:
    camunda:
        image: 'digitalstate/camunda:${IMAGE_TAG}'
        environment:
            - JAVA_OPTS
            - VIRTUAL_HOST

networks:
    default:
        external:
          name: '${NETWORK}'
