version: '2.1'

services:
    camunda:
        build: .
        environment:
            - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Duser.timezone=America/Montreal
            - VIRTUAL_HOST

networks:
    default:
        external:
          name: api_default
