version: '3.4'

services:
  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      default:
        aliases:
          - camunda_database
    ports:
      - 5432:5432

  camunda:
    image: digitalstate/camunda-camunda
    build:
      context: ./camunda
    environment:
      DATABASE_URL: jdbc:postgresql://camunda_database:5432/${DATABASE_NAME}?createDatabaseIfNotExist=true
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 8099:8099

volumes:
  database_data: {}
