version: '2.1'

services:
  camunda:
    build: .
    environment:
      JAVA_OPTS: '${JAVA_OPTS}'
      SERVICE_ENTRYPOINT-PROD: '$${url}'
      SERVICE_ENTRYPOINT-DEV: '$${url}'
      SERVICE_ENTRYPOINT-TEST: '$${url}'
      SERVICE_8000_IGNORE: 'true'
      SERVICE_8080_ID: '${COMPOSE_PROJECT_NAME}_api_http'
      SERVICE_8080_NAME: '${COMPOSE_PROJECT_NAME}_api_http'
      SERVICE_8080_TAGS: 'proxy.enable=true,proxy.tags=external,proxy.frontend.entryPoints=http,proxy.frontend.rule=Host:${API_HOST}'

networks:
  default:
    external:
      name: '${NETWORK}'
