version: '3.4'

services:
  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      default:
        aliases:
          - camunda_database

  camunda:
    image: digitalstate/camunda-camunda
    build:
      context: ./camunda
    environment:
      DATASOURCE_URL: ${CAMUNDA_DATABASE_URL}
      DATASOURCE_USER: ${DATABASE_USER}
      DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      ADMIN_USER: ${CAMUNDA_ADMIN_USER}
      ADMIN_PASSWORD: ${CAMUNDA_ADMIN_PASSWORD}

volumes:
  database_data: {}
